# Halo Robot
# Date: 23th February 2024

##############################################################################
# Frame Ids

base_link : "base_link"
left_marker: "fiducial_10"
centre_marker: "fiducial_20"
right_marker: "fiducial_11"

##############################################################################
# Vel profiles

# the upper lower limit of the cmd_vel output
linear_vel_range: [-0.15, 0.15]
angular_vel_range: [-0.15, 0.15]

# Absolute vel profile
# min (ang and linear) vel here means the min cmd_vel before the robot stalls
max_linear_vel: 0.15         # m/s, for parallel.c and steer
min_linear_vel: 0.05        # m/s, for lastmile
max_angular_vel: 0.15       # rad/s
min_angular_vel: 0.08       # rad/s

##############################################################################
# General Configs

cam_offset: 0.54          # camera to base link
stop_yaw_diff: 0.03        # radian
stop_trans_diff: 0.008      # meters
tf_expiry: 0.8             # sec
controller_rate: 5.0       # hz
dock_timeout: 220          # sec
front_dock: false          # when false, robot dock from behind

##############################################################################
# Predock State

max_parallel_offset: 0.10     # m, will move to parallel.c if exceeded
predock_tf_samples: 3         # tf samples to avg, parallel.c validation

##############################################################################
# Steer Dock State

to_last_mile_dis: 0.50        # edge2edge distance where transition to LM
to_last_mile_tol: 0.20        # transition tolerance from SD to LM
# Determine how "rigorous" we want the robot to correct itself during steer dock
offset_to_angular_vel: 1.0    # multiplier factor to convert y-offset to ang vel

##############################################################################
# Last mile State

max_last_mile_odom: 0.20    # max last mile odom move without using marker
stop_distance: 0.075        # edge2edge distance to stop from charger

##############################################################################
# Activate Charger

enable_charger_srv: True   # whether to activate charger after last mile
check_battery_status: True # check if battery status is POWER_SUPPLY_STATUS_CHARGING
check_battery_timeout: 10.0   # secs
charger_srv_name: "/xnergy_charger_rcu/trigger_charging"  # ros srv
battery_status_topic: "/xnergy_charger_rcu/battery_state" # ros topic

##############################################################################
# Retry State

retry_count: 3             # how many times to retry
retry_retreat_dis: 0.4     # meters, distance retreat during retry

##############################################################################
# Undock State
trigger_stop_charge_srv: "/xnergy_charger_rcu/trigger_stop"
undock_distance: 0.5
cmd_vel_topic: "/kopilot_user_cmd"